# Generated by Django 5.0.7 on 2025-01-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_avatar_alter_myuser_is_2fa_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_2fa_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
