version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres_container2
    environment:
      POSTGRES_USER: django_project_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: django_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: