###
POST http://127.0.0.1:8000/api/user/register/
Content-Type: application/json

{
    "email": "h@gmail.com",
    "user_name": "9",
    "password": "123"
}

###
POST http://127.0.0.1:8000/api/user/login/
Content-Type: application/json

{
    "email": "h@gmail.com",
    "password": "123"
}

###
GET http://127.0.0.1:8000/api/user/check/token/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzEwODQ3LCJpYXQiOjE3Mzc3MDk5NDcsImp0aSI6ImZlNGQ4MjJhNTRhMzQyYzJhODA0NDA5NTZhYmM1ODUzIiwidXNlcl9pZCI6MX0.IYjpggBMK3bXxZ6iKgQIuxZJan8BT5w5qfGQLJcZJ7s
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzc5NjM0NywiaWF0IjoxNzM3NzA5OTQ3LCJqdGkiOiI4N2ZlNGZiYzc2YzU0MjcxOWZmMjE3OWEyZDdjNjZlYiIsInVzZXJfaWQiOjF9.oP4cJZR9R1QBjWWWwrIUK3uE2NyOsBcRqaCVYD0qbQw

###
POST http://127.0.0.1:8000/api/user/refresh/token/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzMzNjAwLCJpYXQiOjE3Mzc3MzI2OTYsImp0aSI6ImQ1ZWQ5MGU1Y2RmYzQxNjFhZDhhMDFmNjM4OGM5YmUyIiwidXNlcl9pZCI6Mn0.Z98B831AoTDEvNe5GAD_VaKdxfyBi2DBb_xcwin83rk
# refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzgxOTEwMCwiaWF0IjoxNzM3NzMyNzAwLCJqdGkiOiJlNzU5MDNiMWMwYTQ0NzEzYmFkMWEwNmRlNWRhZTUxYyIsInVzZXJfaWQiOjJ9.-TOuVcSWKQDKIFcRYElBiOBVRIFN9g0uHXadG_EEobk
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzg3MTQ5NSwiaWF0IjoxNzM3Nzg1MDk1LCJqdGkiOiI5NjdlOGU4ZmEyZGU0ZWVhYmUxNGUwZDFhNzgxMjYzYSIsInVzZXJfaWQiOjV9.S7XNooxCBMTIzYzYumJ2r-IXJdqznWi9Yp722vNScHo"
}

###
GET http://127.0.0.1:8000/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzg2OTQ2LCJpYXQiOjE3Mzc3ODUwOTUsImp0aSI6ImEyZWViYmMyYmEwNDRiMTI4NGJkNjgwZTg5OThjNWMzIiwidXNlcl9pZCI6NX0.s5WlyMjI1HU2GvITEWLCcFSKLOd8Uf0HZGl1QSoC6cs
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzg3MjQ0NiwiaWF0IjoxNzM3Nzg2MDQ2LCJqdGkiOiI1NWUwZTExYjAzMDM0MTMwOTUwNjYyYjRiOGE4NmYzZSIsInVzZXJfaWQiOjV9.TWZDeFYCC_GA1FNKu8ObVPJSq3zMQt41h3z-t2kzE1g
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/user/profile/nabboune
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NjkxMDUzLCJpYXQiOjE3Mzc2OTAxNTMsImp0aSI6IjJkYzQ2ZTI4MTEzNDRiZmZiNmY0NDE4Njk3YTUyMDVkIiwidXNlcl9pZCI6NH0.qXzdXwBR5-KE6qQpBcMZM8QqkkyxjLfK-T8mM-8PCd4
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzc3NjU1MywiaWF0IjoxNzM3NjkwMTUzLCJqdGkiOiJjMDczMDEyNTg5N2E0YWQ0OTYyODZlODY5NDkxMjQ3YyIsInVzZXJfaWQiOjR9.fktbATeWccabJHEhTut2m4aAr1U6kkbo41BuVg48UcQ

###
GET http://127.0.0.1:8000/search/bla
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NTQ5MTc5LCJpYXQiOjE3Mzc1NDgyNzksImp0aSI6IjJkODVkNjY4MGU4OTQ3NDdhMWU3NTc0NzgwODdlZTk4IiwidXNlcl9pZCI6Mn0.TtWhSP-jDon1ZDTPMD1zlrKsCzR3Qvcd-uhP320Wjtw
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NTQ5MjQwLCJpYXQiOjE3Mzc1NDgzNDAsImp0aSI6ImZlOWEzM2I1ZDAwZjRmYzc4NjJhNDBkOGZiMTNjMzNjIiwidXNlcl9pZCI6M30.HD_3djNZEr03tpibXNHagl26m-Le0sc9oSo9_BA3ylg

###
POST http://localhost:8000/api/friends/friend-requests/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzg3NzA1LCJpYXQiOjE3Mzc3ODY4MDUsImp0aSI6ImYyMGFjOWNhMDAxNzQ3ZDJiZjY1OGQzYmEwNDI3ZDk3IiwidXNlcl9pZCI6OX0.VkODXJKnurP7mn3Ip-zoaqTytRtcuqxG8IDTda8lUbw
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzg3MzIwNSwiaWF0IjoxNzM3Nzg2ODA1LCJqdGkiOiI0NTBlYzI4YjIzYzQ0MjBiYjdkZjMyZDQwOTlhYTY3NCIsInVzZXJfaWQiOjl9.AvZMvy7mLJP_6kKQyAbEXxwghn-Yb39AHAyc-gCez-Y
Content-Type: application/json

{
    "receiver": "8"
}


###
POST http://localhost:8000/api/friends/friend-requests/accept/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzg3MDk4LCJpYXQiOjE3Mzc3ODYxOTgsImp0aSI6IjZkNzkwZjQzMWFjODQwNzI5NjY3NWQ0YmEwYmU0NTBjIiwidXNlcl9pZCI6Nn0.JXaW2F4HlwJ_dGHQjpdONU-vg7txTZZnY75D0jYRNGw
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzg3MjU5OCwiaWF0IjoxNzM3Nzg2MTk4LCJqdGkiOiIwOTM3NmMxMWVhNWY0MDc2YTY0ZmUzZGJhMThiMmRiMyIsInVzZXJfaWQiOjZ9.2-G61vbrMz0Sz7asN4VPWDVpLlK7tVFWfCfeGH6p4Ag
Content-Type: application/json

{
    "user_id": "7"
}

###
POST http://localhost:8000/api/friends/friend-requests/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzg2OTQ2LCJpYXQiOjE3Mzc3ODUwOTUsImp0aSI6ImEyZWViYmMyYmEwNDRiMTI4NGJkNjgwZTg5OThjNWMzIiwidXNlcl9pZCI6NX0.s5WlyMjI1HU2GvITEWLCcFSKLOd8Uf0HZGl1QSoC6cs
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzg3MjQ0NiwiaWF0IjoxNzM3Nzg2MDQ2LCJqdGkiOiI1NWUwZTExYjAzMDM0MTMwOTUwNjYyYjRiOGE4NmYzZSIsInVzZXJfaWQiOjV9.TWZDeFYCC_GA1FNKu8ObVPJSq3zMQt41h3z-t2kzE1g
Content-Type: application/json

{
    "receiver": "4"
}

###
GET http://127.0.0.1:8000/api/friends/friend-request/cancel/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzg3NzA1LCJpYXQiOjE3Mzc3ODY4MDUsImp0aSI6ImYyMGFjOWNhMDAxNzQ3ZDJiZjY1OGQzYmEwNDI3ZDk3IiwidXNlcl9pZCI6OX0.VkODXJKnurP7mn3Ip-zoaqTytRtcuqxG8IDTda8lUbw
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzg3MzIwNSwiaWF0IjoxNzM3Nzg2ODA1LCJqdGkiOiI0NTBlYzI4YjIzYzQ0MjBiYjdkZjMyZDQwOTlhYTY3NCIsInVzZXJfaWQiOjl9.AvZMvy7mLJP_6kKQyAbEXxwghn-Yb39AHAyc-gCez-Y


###
GET http://localhost:8000/api/friends/friends/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzg3MDk4LCJpYXQiOjE3Mzc3ODYxOTgsImp0aSI6IjZkNzkwZjQzMWFjODQwNzI5NjY3NWQ0YmEwYmU0NTBjIiwidXNlcl9pZCI6Nn0.JXaW2F4HlwJ_dGHQjpdONU-vg7txTZZnY75D0jYRNGw
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzg3MjU5OCwiaWF0IjoxNzM3Nzg2MTk4LCJqdGkiOiIwOTM3NmMxMWVhNWY0MDc2YTY0ZmUzZGJhMThiMmRiMyIsInVzZXJfaWQiOjZ9.2-G61vbrMz0Sz7asN4VPWDVpLlK7tVFWfCfeGH6p4Ag
Content-Type: application/json

###
GET http://localhost:8000/api/friends/notifications/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzg3NjU5LCJpYXQiOjE3Mzc3ODY3NTksImp0aSI6IjEyMmExMmE5MzA0YjQ4Y2I5ZWJjM2VlMGM2NmY0ODAxIiwidXNlcl9pZCI6OH0.7emkT7EwCgkwyWbAEPoYK-BO-MByZCx8uAH1aMNcXgg
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzg3MzE1OSwiaWF0IjoxNzM3Nzg2NzU5LCJqdGkiOiJlYjliMDk0MmU1YWI0ODY2OTEwMTU1Mjc0YmYyMzhkMCIsInVzZXJfaWQiOjh9.lQ3ZKz9WuIpCxyLM0xYbH-Tt9ilibTcY4sUYDeovX2M
Content-Type: application/json
