# Generated by Django 5.0.7 on 2024-12-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nickename',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='nickename'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='oauth_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='oauth_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
