# Generated by Django 5.0.7 on 2025-01-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_is_2fa_active_otpuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/op.webp', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_2fa_active',
            field=models.BooleanField(default=True),
        ),
    ]
