version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tr_django_app
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgres://django_project_user:123@db:5432/django_project
      - DJANGO_SETTINGS_MODULE=ft_transcendence.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:latest
    container_name: tr_postgres_db
    environment:
      POSTGRES_USER: django_project_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: django_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    container_name: tr_redis
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: